# Generated by Django 4.1.1 on 2023-07-28 09:31

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=100000000000, null=True)),
                ('thumbnail', models.ImageField(upload_to='images_blog/')),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
